### PR TITLE
8.x-1.x

### PR DESCRIPTION
**Pull request by welly**
Created a new 8.x-1.x branch, cleaned up the module a little bit. Feel free to pull it in or not! Would be good if you could publish this on drupal.org otherwise would you be happy for me to do so?

Cheers and nice little module! Just what I needed!

### CODE REVIEW

**Comment by chrishappy** [comment]
Feel free to publish it on drupal.org as I won't have the time or expertise to be able to maintain it.
Thanks for the improvements and God bless.

**Comment by welly** [comment]
Fab, thanks very much for getting started with the module! I'm happy to take it on and maintain it.

Cheers!

**Comment by dravenk** [comment]
@welly @Chris-Happy7 
I had posted to drupal.org last week.
Because I credited a issue but no one notice.
https://github.com/Chris-Happy7/d8-time-range/issues/2

See 
https://www.drupal.org/project/time_range  

Also on github.com
https://github.com/DravenK/time-range

**Comment by welly** [comment]
I didn't see this module or git repo until three days ago. Thanks for posting it on drupal.org, I'll have a few patches for you soon!

Thanks!

**Comment by dravenk** [comment]
Must thanks @Chris-Happy7 . Thanks for give me a good start.  
@welly 
Besides, I very much hope you can correct the README.md.

**Comment by chrishappy** [comment]
Your welcome everyone! Thanks for taking it on!

Merry Christmas and God bless!

**Pull request merged**
